// ::: Code Generated by Copilot e4f5a6b7-8c9d-4e01-8f23-4a5b6c7d8e9f. This comment will be removed automatically after the file is saved :::
// Application entry point: wires DOM events and boots the app.

import { state, saveProjects, restoreProfile, currentProject } from './store.js';
import { showToast, setLoginStatus, clearLoginStatus, showBusy, hideBusy } from './feedback.js';
import { byId } from './utils.js';
import { signIn, signOut, trySilentSignIn } from './auth.js';
import { createArtifact, syncProjectArtifacts, saveProjectStatus, saveProjectDetails, createRecordingArtifact, createLinkArtifact, recordProjectCompleted, hydrateProjects, loadProjectMetadata, deleteProject } from './drive.js';
import { refreshAllSources, refreshActiveSource, ensureActiveSourceLoaded } from './sources.js';
import { setActiveView } from './shell.js';
import { ovTagRowHtml } from './projects.js';
import { openRecorder, closeRecorder, isRecorderOpen, wireRecorder } from './recorder.js';
import {
  openProjectModal,
  closeProjectModal,
  handleProjectSubmit,
  addTagRow,
  openArtifactModal,
  closeArtifactModal,
  submitArtifactModal,
  syncArtifactName,
  openLinkModal,
  closeLinkModal,
  submitLinkModal,
} from './modals.js';
import { render } from './render.js';
import { refreshInsights } from './insights.js';

function goToView(viewName) {
  if (viewName === 'projects') {
    state.selectedProjectId = null;
    state.selectedProjectCategory = null;
    state.selectedProjectStatus = 'all';
    state.selectedProjectTab = 'overview';
  }
  setActiveView(viewName);
  render();
  if (viewName === 'insights') refreshInsights();
}

function openProjectFromItem(item) {
  if (!item || !item.title) {
    showToast('This item has no title to turn into a project.');
    return;
  }
  openProjectModal(item);
}

// Jump to the project already created from an inbox item.
async function openExistingProjectFromInbox(projectId) {
  state.activeView = 'projects';
  await openProject(projectId);
}

async function loadProjectsFromDrive() {
  state.projectsLoading = true;
  render();
  try {
    await hydrateProjects();
  } finally {
    state.projectsLoading = false;
    render();
  }
}

async function openProject(projectId) {
  state.selectedProjectId = projectId;
  state.selectedProjectTab = 'overview';
  state.editingOverview = false;
  const project = currentProject();
  if (project) state.selectedProjectCategory = project.category || 'Others';
  render();

  if (project) {
    try {
      // Lazily restore the source bookmark for projects hydrated from the Drive index.
      if (project.bookmark === undefined) {
        const meta = await loadProjectMetadata(project);
        if (meta) {
          project.bookmark = meta.bookmark || null;
          saveProjects();
          render();
        }
      }
      await syncProjectArtifacts(project);
      render();
    } catch {
      /* keep locally cached artifacts */
    }
  }
}

async function addArtifactFlow(trigger) {
  const project = currentProject();
  if (!project) return;
  const result = await openArtifactModal(trigger);
  if (!result) return;
  const { type, name, label } = result;

  showBusy('Creating ' + String(label || 'file').toLowerCase() + '…');
  try {
    const artifact = await createArtifact(project, name, type);
    state.selectedProjectArtifactId = artifact.id;
    state.selectedProjectTab = 'docs';
    render();
    window.open(artifact.url, '_blank', 'noopener,noreferrer');
  } catch (error) {
    showToast(error.message || 'Could not create the file.');
  } finally {
    hideBusy();
  }
}

async function updateProjectMeta(changes) {
  const project = currentProject();
  if (!project) return;
  const wasComplete = Number(project.progress) >= 100 || project.status === 'Complete';
  Object.assign(project, changes);
  saveProjects();
  render();
  try {
    await saveProjectStatus(project);
    const isComplete = Number(project.progress) >= 100 || project.status === 'Complete';
    if (!wasComplete && isComplete) await recordProjectCompleted(project);
  } catch (error) {
    showToast(error.message || 'Saved locally. Google Drive sync failed.');
  }
}

function gatherOverviewTags() {
  const container = byId('ov-tags');
  if (!container) return [];
  return Array.from(container.querySelectorAll('.tag-input-row'))
    .map((row) => {
      const inputs = row.querySelectorAll('input');
      const key = (inputs[0]?.value || '').trim();
      const value = (inputs[1]?.value || '').trim();
      return key || value ? { key, value } : null;
    })
    .filter(Boolean);
}

async function saveOverviewEdits() {
  const project = currentProject();
  if (!project) return;
  const name = (byId('ov-name')?.value || '').trim();
  if (!name) {
    showToast('Project name is required.');
    return;
  }
  const duplicate = state.projects.some(
    (other) => other.id !== project.id && other.name.toLowerCase() === name.toLowerCase()
  );
  if (duplicate) {
    showToast('Another project already uses this name.');
    return;
  }

  Object.assign(project, {
    name,
    title: name,
    category: byId('ov-category')?.value || project.category,
    description: byId('ov-description')?.value || '',
    tags: gatherOverviewTags(),
  });
  state.editingOverview = false;
  saveProjects();
  render();
  try {
    await saveProjectDetails(project);
  } catch (error) {
    showToast(error.message || 'Saved locally. Google Drive sync failed.');
  }
}

async function recordArtifactFlow() {
  const project = currentProject();
  if (!project) return;
  const result = await openRecorder();
  if (!result) return;

  showBusy('Saving recording…');
  try {
    const artifact = await createRecordingArtifact(project, result);
    state.selectedProjectArtifactId = artifact.id;
    state.selectedProjectTab = 'recordings';
    render();
    if (artifact.url) window.open(artifact.url, '_blank', 'noopener,noreferrer');
  } catch (error) {
    showToast(error.message || 'Could not save the recording.');
  } finally {
    hideBusy();
  }
}

async function addLinkFlow() {
  const project = currentProject();
  if (!project) return;
  const result = await openLinkModal();
  if (!result) return;

  showBusy('Saving link…');
  try {
    const artifact = await createLinkArtifact(project, result);
    state.selectedProjectArtifactId = artifact.id;
    state.selectedProjectTab = 'links';
    render();
  } catch (error) {
    showToast(error.message || 'Could not save the link.');
  } finally {
    hideBusy();
  }
}

function openArtifact(artifactId) {
  const project = currentProject();
  if (!project) return;
  const artifact = (project.artifacts || []).find((entry) => String(entry.id) === String(artifactId));
  if (artifact && artifact.url) {
    state.selectedProjectArtifactId = artifact.id;
    render();
    window.open(artifact.url, '_blank', 'noopener,noreferrer');
  }
}

function removeProject(projectId) {
  const target = state.projects.find((project) => project.id === projectId) || null;
  state.projects = state.projects.filter((project) => project.id !== projectId);
  if (state.selectedProjectId === projectId) {
    state.selectedProjectId = null;
    state.selectedProjectTab = 'overview';
  }
  const stillHasCategory = state.projects.some(
    (project) => (project.category || 'Others') === state.selectedProjectCategory
  );
  if (!stillHasCategory) state.selectedProjectCategory = null;
  saveProjects();
  render();
  showToast('Project removed.');
  if (target) {
    deleteProject(target).catch(() => showToast('Removed here, but Google Drive cleanup failed.'));
  }
}

function handleBreadcrumb(target, value) {
  if (target === 'root') {
    state.selectedProjectId = null;
    state.selectedProjectCategory = null;
    state.selectedProjectStatus = 'all';
  } else if (target === 'category') {
    state.selectedProjectId = null;
    state.selectedProjectCategory = value || null;
    state.selectedProjectStatus = 'all';
  } else if (target === 'project') {
    state.selectedProjectTab = 'overview';
  }
  render();
}

function wireAuth() {
  const signInButton = byId('btn-signin');
  if (signInButton) {
    signInButton.addEventListener('click', async () => {
      clearLoginStatus();
      const label = signInButton.textContent;
      signInButton.disabled = true;
      signInButton.textContent = 'Signing in…';
      try {
        await signIn();
        render();
        await loadProjectsFromDrive();
        await refreshAllSources();
        showToast('Signed in.');
      } catch (error) {
        setLoginStatus(error.message || 'Sign-in failed.', true);
      } finally {
        signInButton.disabled = false;
        signInButton.textContent = label;
      }
    });
  }

  const signOutButton = byId('btn-signout');
  if (signOutButton) {
    signOutButton.addEventListener('click', () => {
      signOut();
      render();
      showToast('Signed out.');
    });
  }

  const avatarMenu = byId('user-menu-toggle');
  if (avatarMenu) {
    avatarMenu.addEventListener('click', () => {
      byId('user-menu')?.classList.toggle('is-open');
    });
    document.addEventListener('click', (event) => {
      if (!event.target.closest('.user-menu')) byId('user-menu')?.classList.remove('is-open');
    });
  }
}

function wireNav() {
  document.querySelectorAll('.nav-link').forEach((button) => {
    button.addEventListener('click', () => goToView(button.dataset.view));
  });

  const breadcrumbs = byId('breadcrumbs');
  if (breadcrumbs) {
    breadcrumbs.addEventListener('click', (event) => {
      const crumb = event.target.closest('[data-crumb]');
      if (crumb) handleBreadcrumb(crumb.dataset.crumb, crumb.dataset.crumbValue);
    });
  }
}

function wireInbox() {
  document.querySelectorAll('.source-tab').forEach((button) => {
    button.addEventListener('click', async () => {
      const nextSource = button.dataset.source;
      if (!nextSource || nextSource === state.activeSource) return;
      state.activeSource = nextSource;
      render();
      if (state.profile && state.token) {
        try {
          await ensureActiveSourceLoaded();
        } catch {
          showToast('Source sync failed.');
        }
      }
    });
  });

  byId('btn-inbox-refresh')?.addEventListener('click', async () => {
    if (!state.profile || !state.token) return;
    try {
      await refreshActiveSource({ force: true });
    } catch {
      showToast('Refresh failed.');
    }
  });

  // Revalidate stale items when the tab regains focus, without polling.
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible' && state.profile && state.token) {
      ensureActiveSourceLoaded();
    }
  });

  const dateFilter = byId('date-filter');
  if (dateFilter) {
    dateFilter.addEventListener('change', () => {
      state.activeDateFilter = dateFilter.value || 'all';
      render();
    });
  }

  const list = byId('inbox-list');
  if (list) {
    list.addEventListener('click', (event) => {
      const row = event.target.closest('[data-inbox-item]');
      if (!row) return;
      if (row.dataset.existingProject) {
        openExistingProjectFromInbox(row.dataset.existingProject);
        return;
      }
      try {
        openProjectFromItem(JSON.parse(row.dataset.inboxItem));
      } catch {
        showToast('Could not open this item.');
      }
    });
  }
}

function wireProjects() {
  const list = byId('project-list');
  if (list) {
    list.addEventListener('click', (event) => {
      const crumb = event.target.closest('[data-crumb]');
      if (crumb) {
        handleBreadcrumb(crumb.dataset.crumb, crumb.dataset.crumbValue);
        return;
      }
      if (event.target.closest('[data-new-project]')) {
        openProjectModal(null, { category: state.selectedProjectCategory });
        return;
      }
      const categoryCard = event.target.closest('[data-category]');
      if (categoryCard) {
        state.selectedProjectCategory = categoryCard.dataset.category;
        state.selectedProjectStatus = 'all';
        render();
        return;
      }
      const statusFilter = event.target.closest('[data-status-filter]');
      if (statusFilter) {
        state.selectedProjectStatus = statusFilter.dataset.statusFilter;
        render();
        return;
      }
      const remove = event.target.closest('[data-remove-project]');
      if (remove) {
        removeProject(remove.dataset.removeProject);
        return;
      }
      const openBtn = event.target.closest('[data-project-id]');
      if (openBtn) openProject(openBtn.dataset.projectId);
    });
  }

  const workspace = byId('project-workspace');
  if (workspace) {
    workspace.addEventListener('click', (event) => {
      const tab = event.target.closest('[data-project-tab]');
      if (tab) {
        state.selectedProjectTab = tab.dataset.projectTab;
        state.selectedProjectArtifactId = null;
        state.editingOverview = false;
        render();
        return;
      }
      if (event.target.closest('[data-project-back]')) {
        state.selectedProjectId = null;
        state.editingOverview = false;
        render();
        return;
      }
      if (event.target.closest('[data-edit-overview]')) {
        state.editingOverview = true;
        render();
        return;
      }
      if (event.target.closest('[data-cancel-overview]')) {
        state.editingOverview = false;
        render();
        return;
      }
      if (event.target.closest('[data-save-overview]')) {
        saveOverviewEdits();
        return;
      }
      if (event.target.closest('[data-ov-add-tag]')) {
        byId('ov-tags')?.insertAdjacentHTML('beforeend', ovTagRowHtml());
        return;
      }
      if (event.target.closest('[data-ov-remove-tag]')) {
        event.target.closest('.tag-input-row')?.remove();
        return;
      }
      if (event.target.closest('[data-project-complete]')) {
        updateProjectMeta({ progress: 100, status: 'Complete' });
        return;
      }
      const add = event.target.closest('[data-add-artifact]');
      if (add) {
        addArtifactFlow(add.dataset.addArtifact);
        return;
      }
      if (event.target.closest('[data-record-artifact]')) {
        recordArtifactFlow();
        return;
      }
      if (event.target.closest('[data-add-link]')) {
        addLinkFlow();
        return;
      }
      const open = event.target.closest('[data-open-artifact]');
      if (open) openArtifact(open.dataset.openArtifact);
    });

    workspace.addEventListener('input', (event) => {
      const slider = event.target.closest('[data-project-progress]');
      if (!slider) return;
      const percent = Math.max(0, Math.min(100, Number(slider.value) || 0));
      const label = workspace.querySelector('[data-progress-label]');
      const fill = workspace.querySelector('[data-progress-fill]');
      if (label) label.textContent = percent + '%';
      if (fill) fill.style.width = percent + '%';
    });

    workspace.addEventListener('change', (event) => {
      const slider = event.target.closest('[data-project-progress]');
      if (slider) {
        const percent = Math.max(0, Math.min(100, Number(slider.value) || 0));
        updateProjectMeta({ progress: percent, status: percent >= 100 ? 'Complete' : 'In progress' });
      }
    });
  }
}

function wireModals() {
  byId('project-form')?.addEventListener('submit', handleProjectSubmit);
  byId('btn-add-tag')?.addEventListener('click', addTagRow);
  byId('btn-close-modal')?.addEventListener('click', closeProjectModal);
  byId('btn-cancel-modal')?.addEventListener('click', closeProjectModal);
  byId('project-modal')?.addEventListener('click', (event) => {
    if (event.target.dataset.closeModal === 'true') closeProjectModal();
  });

  byId('artifact-form')?.addEventListener('submit', submitArtifactModal);
  byId('artifact-type')?.addEventListener('change', syncArtifactName);
  byId('btn-artifact-cancel')?.addEventListener('click', () => closeArtifactModal(null));
  byId('btn-artifact-close')?.addEventListener('click', () => closeArtifactModal(null));
  byId('artifact-modal')?.addEventListener('click', (event) => {
    if (event.target.dataset.closeModal === 'true') closeArtifactModal(null);
  });

  byId('link-form')?.addEventListener('submit', submitLinkModal);
  byId('btn-link-cancel')?.addEventListener('click', () => closeLinkModal(null));
  byId('btn-link-close')?.addEventListener('click', () => closeLinkModal(null));
  byId('link-modal')?.addEventListener('click', (event) => {
    if (event.target.dataset.closeModal === 'true') closeLinkModal(null);
  });

  document.addEventListener('keydown', (event) => {
    if (event.key !== 'Escape') return;
    if (isRecorderOpen()) closeRecorder();
    else if (byId('link-modal')?.classList.contains('is-open')) closeLinkModal(null);
    else if (byId('artifact-modal')?.classList.contains('is-open')) closeArtifactModal(null);
    else if (byId('project-modal')?.classList.contains('is-open')) closeProjectModal();
  });
}

function wireEvents() {
  wireAuth();
  wireNav();
  wireInbox();
  wireProjects();
  wireModals();
  wireRecorder();
}

async function init() {
  state.profile = restoreProfile();
  wireEvents();
  render();

  await trySilentSignIn();
  render();

  if (state.profile && state.token) {
    await loadProjectsFromDrive();
    await refreshAllSources();
  }
}

init().catch((error) => {
  setLoginStatus(error.message || 'App initialization failed.', true);
});
