// ::: Code Generated by Copilot 6c3f8e5d-0a4b-4e39-9c7f-2d9a5b3e4c8a. This comment will be removed automatically after the file is saved :::
// App shell: user identity, primary navigation and breadcrumbs.

import { state, currentProject } from './store.js';
import { byId, escapeHtml } from './utils.js';

const TAB_LABELS = { overview: 'Overview', docs: 'Docs', recordings: 'Recordings', links: 'Links' };

export function renderUser() {
  const gate = byId('login-gate');
  const shell = byId('app-shell');

  if (!state.profile) {
    if (gate) gate.classList.remove('hidden');
    if (shell) shell.classList.add('hidden');
    return;
  }

  if (gate) gate.classList.add('hidden');
  if (shell) shell.classList.remove('hidden');

  const name = byId('user-name');
  const email = byId('user-email');
  const avatar = byId('user-avatar');
  if (name) name.textContent = state.profile.name;
  if (email) email.textContent = state.profile.email;
  if (avatar) {
    avatar.src = state.profile.picture || '';
    avatar.alt = state.profile.name || '';
  }
}

export function setActiveView(viewName) {
  state.activeView = viewName;
  document.querySelectorAll('.nav-link').forEach((button) => {
    button.classList.toggle('is-active', button.dataset.view === viewName);
  });
  document.querySelectorAll('.view').forEach((view) => {
    view.classList.toggle('is-active', view.id === 'view-' + viewName);
  });
}

export function renderShell() {
  const bar = byId('breadcrumbs');
  if (!bar) return;

  if (state.activeView !== 'projects') {
    bar.classList.add('hidden');
    bar.innerHTML = '';
    return;
  }

  const crumbs = [{ label: 'Projects', target: 'root' }];
  const project = currentProject();
  if (project) {
    crumbs.push({ label: project.category || 'Others', target: 'category', value: project.category || 'Others' });
    crumbs.push({ label: project.name, target: 'project' });
    crumbs.push({ label: TAB_LABELS[state.selectedProjectTab] || 'Overview' });
  } else if (state.selectedProjectCategory) {
    crumbs.push({ label: state.selectedProjectCategory });
  }

  bar.classList.remove('hidden');
  bar.innerHTML = crumbs
    .map((crumb, index) => {
      const isLast = index === crumbs.length - 1;
      const content = escapeHtml(crumb.label);
      const node = isLast || !crumb.target
        ? '<span class="crumb crumb--current">' + content + '</span>'
        : '<button class="crumb" type="button" data-crumb="' + crumb.target + '"' +
          (crumb.value ? ' data-crumb-value="' + escapeHtml(crumb.value) + '"' : '') +
          '>' + content + '</button>';
      return node + (isLast ? '' : '<span class="crumb-sep">›</span>');
    })
    .join('');
}
